{"name": "test_mp_login[13812345678-246810-哈哈]", "status": "broken", "statusDetails": {"message": "FileNotFoundError: [Errno 2] No such file or directory: './image/err.png'", "trace": "self = <scripts.test01_mp_login.TestMpLogin object at 0x0000000003DD6AC8>\nusername = '13812345678', code = '246810', expect = '哈哈'\n\n    @pytest.mark.parametrize(\"username,code,expect\", read_yaml(\"mp_login.yaml\"))\n    def test_mp_login(self, username, code, expect):\n        # 调用登录业务方法\n        self.mp.page_mp_login(username, code)\n        # 断言  让程序代替人工对程序执行的结果验证的过程\n        # print(\"\\n 获取的昵称为：\", self.mp.page_get_nickname())\n        # assert expect == self.mp.page_get_nickname()\n        try:\n>           assert expect == self.mp.page_get_nickname()\nE           AssertionError: assert '哈哈' == '叫我老师'\nE             - 叫我老师\nE             + 哈哈\n\ntest01_mp_login.py:35: AssertionError\n\nDuring handling of the above exception, another exception occurred:\n\nself = <scripts.test01_mp_login.TestMpLogin object at 0x0000000003DD6AC8>\nusername = '13812345678', code = '246810', expect = '哈哈'\n\n    @pytest.mark.parametrize(\"username,code,expect\", read_yaml(\"mp_login.yaml\"))\n    def test_mp_login(self, username, code, expect):\n        # 调用登录业务方法\n        self.mp.page_mp_login(username, code)\n        # 断言  让程序代替人工对程序执行的结果验证的过程\n        # print(\"\\n 获取的昵称为：\", self.mp.page_get_nickname())\n        # assert expect == self.mp.page_get_nickname()\n        try:\n            assert expect == self.mp.page_get_nickname()\n        except Exception as e:\n            print(\"错误原因：\", e)\n>           self.mp.base_get_img()\n\ntest01_mp_login.py:38: \n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _\n..\\base\\base.py:63: in base_get_img\n    self.__base_write_image()\n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _\n\nself = <page.page_mp_login.PageMpLogin object at 0x0000000003E16908>\n\n    def __base_write_image(self):\n        # 获取图片流\n>       with open(\"./image/err.png\", \"rb\") as f:\nE       FileNotFoundError: [Errno 2] No such file or directory: './image/err.png'\n\n..\\base\\base.py:68: FileNotFoundError"}, "parameters": [{"name": "username", "value": "'13812345678'"}, {"name": "code", "value": "'246810'"}, {"name": "expect", "value": "'哈哈'"}], "start": 1595660836756, "stop": 1595660842657, "uuid": "8c38bea2-ef64-427b-8854-c60ab64244de", "historyId": "bd46d53bef102fd0aa8c3b3428b52122", "testCaseId": "b1928a7174b0d14afd7479ec3844ea33", "fullName": "scripts.test01_mp_login.TestMpLogin#test_mp_login", "labels": [{"name": "parentSuite", "value": "scripts"}, {"name": "suite", "value": "test01_mp_login"}, {"name": "subSuite", "value": "TestMpLogin"}, {"name": "host", "value": "ETPUA4SBB4P3FBS"}, {"name": "thread", "value": "6652-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "scripts.test01_mp_login"}]}